@startuml
left to right direction

package Model{
	class Pet{
		-pid
		-tid
		-birthDate
		-sex
		-price
		-description
	}

	class Type{
		-tid
		-tname
	}

	class User{
		-uid
		-uname
		-password
	}

	class Booking{
		-bid
		-pid
		-uid
		-price
		-bookingDate
		-telNum
	}

	class PetDAO{
		+findAll()
		+findByTid()
		+findByPid()
		+insert()
		+update()
		+delete()
	}

	class TypeDAO{
		+findAll()
		+findByTid()
		+insert()
		+delete()
	}

	class UserDAO{
		+login()
	}

	class BookingDAO{
		+findAll()
		+findByUid()
		+insert()
		+delete()
	}
}

package Servlet{
	class TopScreenServlet{
		+get()
		+post()
	}

	class PetListServlet{
		+get()
		+post()
	}

	class LoginServlet{
		+get()
		+post()
	}

	class PetInsertServlet{
		+get()
		+post()
	}

	class PetUpdateServlet{
		+get()
		+post()
	}

	class PetDeleteServlet{
		+get()
		+post()
	}

	class TypeInsertServlet{
		+get()
		+post()
	}

	class TypeDeleteServlet{
		+get()
		+post()
	}

	class BookingCheckServlet{
		+get()
		+post()
	}

	class BookingListServlet{
		+get()
		+post()
	}

	class BookingDeleteServlet{
		+get()
		+post()
	}
}


PetListServlet..>TypeDAO
TypeInsertServlet..>TypeDAO
TypeDeleteServlet..>TypeDAO
PetListServlet..>PetDAO
PetInsertServlet..>PetDAO
PetUpdateServlet..>PetDAO
PetDeleteServlet..>PetDAO
LoginServlet..>UserDAO
BookingCheckServlet..>BookingDAO
BookingListServlet..>BookingDAO
BookingDeleteServlet..>BookingDAO

BookingDAO..>Booking
PetDAO..>Pet
TypeDAO..>Type
UserDAO..>User
@enduml