@startuml
title ペット一覧表示
actor ユーザー
participant TopDiagramServlet
participant ペット一覧画面
database ペットDB
autonumber "#"

ユーザー->TopDiagramServlet:GETリクエスト
TopDiagramServlet->ペット一覧画面:遷移
ペット一覧画面->ペットDB:検索
ペットDB->ペット:生成
ペットDB-->ペット一覧画面:ペット一覧
ペット一覧画面-->ユーザー:表示

@enduml