@startuml
title ペット一覧表示
actor ユーザー
participant PetListServlet
participant Pet
participant Request
participant petlist.jsp
autonumber "#."

ユーザー->PetListServlet:GETリクエスト
PetListServlet->PetDAO**:生成()
PetListServlet->PetDAO++:findByTid()
PetDAO->Pet**:リストを生成
PetDAO-->PetListServlet--:Petリスト
PetListServlet->Request++:setAttribute
Request--
PetListServlet->petlist.jsp:フォワード
petlist.jsp-->ユーザー:表示

@enduml