@startuml
title ペット一覧表示
actor ユーザー
participant TopDiagramServlet
participant TypeDAO
participant Pet
participant Request
participant petlist.jsp
autonumber "#."

ユーザー->TopDiagramServlet:GETリクエスト
TopDiagramServlet->TypeDAO**:生成()
TopDiagramServlet->TypeDAO++:findByTid()
TypeDAO->Pet**:リストを生成
TypeDAO-->TopDiagramServlet--:Petリスト
TopDiagramServlet->Request++:setAttribute
Request--
TopDiagramServlet->petlist.jsp:フォワード
petlist.jsp-->ユーザー:表示

@enduml