@startuml
title ペット予約
actor ユーザー
participant BookingCheckServlet
participant BookingServlet
participant Booking.jsp
participant BookingDAO
participant Booking
participant bookingList
autonumber "#."


ユーザー->BookingCheckServlet : 予約ボタン押下
BookingCheckServlet->PetDAO : 生成()
BookingCheckServlet->TypeDAO : 生成()
BookingCheckServlet->UserDAO : 生成()
BookingCheckServlet->PetDAO : findByPid()
BookingCheckServlet->TypeDAO : findByTid()
BookingCheckServlet->UserDAO : findByUid()
PetDAO-->BookingServlet : Pet
TypeDAO-->BookingServlet : Type
UserDAO-->BookingServlet : User
BookingServlet->Booking.jsp : フォワード
Booking.jsp-->ユーザー : 予約フォーム
ユーザー->Booking.jsp : 入力
Booking.jsp-->BookingCheckServlet : POST()
BookingCheckServlet->BookingDAO : 生成()
BookingCheckServlet->Booking:生成()
BookingCheckServlet->BookingDAO : insert()
BookingCheckServlet->bookingList : リダイレクト
bookingList-->ユーザー : 表示



@enduml