@startuml
title ペット予約
actor ユーザー
participant PetListServlet
participant BookingCheckServlet
participant Booking.jsp
participant BookingDAO
participant PetList.jsp
participant BookingList.jsp
autonumber "#."

ユーザー->PetListServlet : ペット一覧ボタン
PetListServlet->PetList.jsp : フォワード
PetList.jsp->ユーザー : 表示
ユーザー->PetList.jsp : ペット予約ボタン
PetList.jsp ->BookingCheckServlet : GET()
BookingCheckServlet->Booking.jsp : フォワード
Booking.jsp->BookingCheckServlet : POST()
BookingCheckServlet->BookingDAO : 生成()
BookingCheckServlet->BookingDAO : insert()
BookingCheckServlet->PetListServlet : GET()
PetListServlet->PetList.jsp : フォワード
PetList.jsp->ユーザー : 表示
BookingCheckServlet->BookingList.jsp : フォワード
BookingList.jsp->ユーザー : 表示


@enduml