@startuml
title 予約情報更新

autonumber "#."

actor ユーザー
participant BookingUpdateServlet
participant BookingDAO
participant bookingUpdate.jsp

ユーザー -> BookingUpdateServlet : 予約更新ボタン
BookingUpdateServlet -> bookingUpdate.jsp : フォワード
bookingUpdate.jsp -> ユーザー : フォームを表示
ユーザー -> bookingUpdate.jsp : フォームを入力
bookingUpdate.jsp -> BookingUpdateServlet : POST()
BookingUpdateServlet -> BookingDAO : 生成()
BookingUpdateServlet -> BookingDAO : Update()
BookingUpdateServlet ->  bookingList : リダイレクト
bookingList -> ユーザー : 表示()


@enduml