@startuml
title ペット予約
actor ユーザー
participant PetListServlet
participant BookingListServlet
autonumber "#"

ユーザー->BookingListServlet : GET()
BookingListServlet->BookingDAO : 生成()
BookingListServlet->BookingDAO : findAll()
BookingDAO->Booking : リストを生成
BookingDAO->BookingListServlet : Bookingリスト
BookingListServlet->request : setAttribute(Bookingリスト)
BookingListServlet->BookingList.jsp : フォワード
BookingList.jsp->ユーザー : 表示


@enduml