@startuml
left to right direction

package モデル{
class ペット{
	-ペットID
	-種類ID
	-生年月日
	-性別
	-値段
	-説明
}

class 種類{
	-種類ID
	-種類
}

class ユーザー{
	-ユーザーID
	-氏名
	-パスワード
}

class 予約{
	-予約番号
	-ユーザーID
	-ペットID
	-種類ID
	-値段
	-日時
	-電話番号
}

class ペットDB{
	+全ペット検索()
	+種類IDで検索()
	+ペットIDで検索()
	+追加()
	+変更()
	+削除()
}

class 種類DB{
	+全種類検索()
	+種類IDで検索()
	+追加()
	+削除()
}

class ユーザーDB{
	+ユーザー名で検索()
}

class 予約DB{
	+全予約検索()
	+ユーザーIDで検索()
	+追加()
	+削除()
}
}

package 画面{
class トップ画面
class ペット一覧画面
class ログイン画面
class ペット追加画面
class ペット更新画面
class ペット削除画面
class 種類追加画面
class 種類削除画面
class 予約確認画面
class 予約一覧画面
class 予約削除画面

}

ペットDB "1" *-- ペット
種類DB "1" *-- 種類
ユーザーDB "1" *-- ユーザー
予約DB "1" *-- 予約
ペット -> 種類
ペット -> 予約

ペット一覧画面-->種類DB
ペット一覧画面-->ペットDB
ログイン画面-->ユーザーDB
ペット追加画面-->ペットDB
ペット更新画面-->ペットDB
種類追加画面-->種類DB
種類削除画面-->種類DB
ペット削除画面-->ペットDB
予約確認画面-->予約DB
予約一覧画面-->予約DB
予約削除画面-->予約DB

@enduml