@startuml
left to right direction

package モデル{
class ペット{
	-ペットID
	-種類
	-生年月日
	-性別
	-値段
	-説明
}

class 種類{
	-種類ID
	-種類
}

class ユーザー{
	-ユーザーID
	-氏名
	-パスワード
}

class 予約{
	-予約番号
	-ペットID
	-種類ID
	-日時
	-電話番号
	-ペット
	-種類
	-ユーザー
}

class ペットDB{
	+全ペット検索()
	+種類IDで検索()
	+ペットIDで検索()
	+追加()
	+変更()
	+削除()
}

class 種類DB{
	+全種類検索()
	+種類IDで検索()
	+追加()
	+削除()
}

class ユーザーDB{
	+ユーザー名とパスワードで検索、照合()
	+ユーザーIDで検索()
}

class 予約DB{
	+全予約検索()
	+予約IDで検索()
	+ユーザーIDで検索()
	+追加()
	+変更()
	+削除()
}
}

package 機能{
class トップ機能
class ペット一覧機能
class ログイン機能
class ログアウト機能
class ペット追加機能
class ペット更新機能
class ペット削除機能
class 種類追加機能
class 種類削除機能
class 予約機能
class 予約入力機能
class 予約一覧機能
class 予約削除機能

}

ペットDB "1" *-- ペット
種類DB "1" *-- 種類
ユーザーDB "1" *-- ユーザー
予約DB "1" *-- 予約
ペット -> 種類
ペット -> 予約

ペット一覧機能-->種類DB
ペット一覧機能-->ペットDB
ログイン機能-->ユーザーDB
ログアウト機能-->ユーザーDB
ペット追加機能-->ペットDB
ペット更新機能-->ペットDB
種類追加機能-->種類DB
種類削除機能-->種類DB
ペット削除機能-->ペットDB
予約入力機能-->予約DB
予約一覧機能-->予約DB
予約削除機能-->予約DB
予約機能-->予約DB

@enduml