@startuml
title ページ遷移図

topPage : トップページ
petList : ペット一覧
login : GET ログインページ \nPOST ログイン
petAdd : ペット情報追加 \nGET 登録確認 \nPOST 登録
petUpdate : ペット情報編集 \nGET 編集確認 \nPOST 更新
booking : GET 予約確認\nPOST 予約
bDel : 予約削除
bookingUpdate : ユーザー予約情報更新 \nGET 更新確認 \nPOST 更新
bookingList : ユーザー用予約リスト
bManageList : 管理者用予約リスト


[*] --> topPage
topPage --> petList
topPage --> login
login --> login : リンク\nuid\nuname\npass
petList --> petAdd : リンク \n
petAdd --> petAdd : リンク \npid \ntid \ntname \nbirthDate \nsex \nprice
petList --> booking : リンク \npid
booking --> booking : リンク \nuid \nbookingDate \ntelNum
petList --> bookingList : リンク \nuid \npid
bookingList --> bDel : リンク \nbid
petList --> bManageList : リンク \nuid \npid
bManageList --> bDel : リンク \nbid
petList --> petList : リンク \npid \ntid \nbirthDate \n sex\nprice \nloginValue
petList --> petUpdate : リンク \npid
petUpdate --> petUpdate : リンク \npid \ntid \ntname \nbirthDate \nprice
bookingList --> bookingUpdate : リンク \nbid \nuid
bManageList --> bookingUpdate : リンク \nbid \nuid
bookingUpdate --> bookingUpdate : リンク \nbid \nuid \nbookingDate


@enduml