@startuml
title ペット一覧表示
actor ユーザー
participant トップ画面
participant ペット一覧画面
database ペットDB

ユーザー->トップ画面:1.ペット一覧ボタン
トップ画面->ペット一覧画面:2.遷移
ペット一覧画面->ペットDB:3.検索
ペットDB->ペット:4.生成
ペットDB-->ペット一覧画面:5.ペット一覧
ペット一覧画面-->ユーザー:6.表示

@enduml