@startuml
title 予約情報削除

autonumber "#."

actor ユーザー
participant 予約一覧画面
participant 予約削除確認画面
database 予約DB

ユーザー -> 予約一覧画面 : 予約削除ボタン
予約一覧画面 -> 予約削除確認画面 : 遷移
予約削除確認画面 -> ユーザー : 確認ボタンを表示
ユーザー -> 予約削除確認画面 : 確認ボタンを押下
予約削除確認画面 -> 予約DB : 削除()
予約削除確認画面 ->  予約一覧画面: 遷移
 予約一覧画面 -> ユーザー : 表示()


@enduml