@startuml
title ペット予約
actor ユーザー
participant ペット一覧画面
participant 予約確認画面
database ペットDB
participant ペット
database 予約DB

ユーザー->ペット一覧画面:1.予約ボタン
ペット一覧画面->予約確認画面:2.遷移
予約確認画面->ペットDB:3.ペット検索
ペットDB->ペット:4.生成
ペットDB-->予約確認画面:5.ペット
予約確認画面-->ユーザー:6.表示
ユーザー->予約確認画面:7.確認ボタン
予約確認画面->予約DB:8.追加

@enduml