@startuml
title ペット削除
actor ユーザー
participant ペット一覧画面
participant ペット削除画面
database ペットDB
autonumber "#"

ユーザー->ペット一覧画面:削除ボタン
ペット一覧画面->ペット削除画面:遷移
ペット削除画面->ペットDB:検索
ペットDB->ペット:生成
ペットDB-->ペット削除画面:ペット
ペット削除画面-->ユーザー:表示
ユーザー->ペット削除画面:確定ボタン
ペット削除画面->ペットDB:削除

@enduml