@startuml
title 予約情報更新

actor ユーザー

ユーザー -> thread.jsp : 入力
thread.jsp -> threadServlet : POST
threadServlet -> threadDAO : New()
threadServlet -> thread : New()
threadServlet -> threadDAO : insert()
threadServlet -> threadPage : sendRedirect()
threadPage -> ユーザー : 表示

@enduml