@startuml
title ペット追加
actor ユーザー
participant ペット一覧画面
participant ペット追加画面
database ペットDB



ユーザー->ペット一覧画面:1.追加ボタン
ペット一覧画面->ペット追加画面:2.遷移
ユーザー->ペット追加画面:3.ペット情報を入力
ユーザー->ペット追加画面:4.確定ボタン
ペット追加画面->ペットDB:5.追加


@enduml