@startuml
left to right direction
actor ユーザー
actor 管理者

rectangle ペット紹介Sysytem{
	ユーザー --> (閲覧)
	ユーザー --> (検索)
	ユーザー --> (予約)

	(閲覧)<--管理者
	(検索)<--管理者
	(予約)<--管理者
	(追加)<--管理者
	(編集)<--管理者
	(削除)<--管理者
	(予約確認)<--管理者
	(ログイン・ログアウト)<--管理者
}
@enduml