@startuml
left to right direction
actor ユーザ
actor 管理者

rectangle ペット紹介Sysytem{
	ユーザ --> (閲覧)
	ユーザ --> (検索)
	ユーザ --> (予約)

	管理者 --> (閲覧)
	管理者 --> (検索)
	管理者 --> (予約)
	管理者 --> (追加)
	管理者 --> (編集)
	管理者 --> (削除)
	管理者 --> (ログイン・ログアウト)
}
@enduml