@startuml
left to right direction
actor ユーザー
actor 管理者

rectangle ペット紹介Sysytem{
	ユーザー --> (ペット情報一覧表示機能)
	ユーザー --> (ペット予約機能)
	ユーザー --> (ユーザーペット予約情報更新機能)
	ユーザー --> (ユーザーペット予約削除機能)
	ユーザー --> (ユーザーペット予約一覧表示機能)
	ユーザー --> (ログイン・ログアウト機能)

	 (ペット情報一覧表示機能)     <--管理者
	(ペット予約機能)     <--管理者
	(管理者ペット予約情報変更機能) <--管理者
	(管理者ペット予約情報削除機能) <--管理者
	(管理者ペット予約一覧表示機能) <--管理者
	(ログイン・ログアウト機能)<--管理者
	(ペット情報追加機能)     <--管理者
	(ペット情報更新機能)     <--管理者
	(ペット情報削除機能)     <--管理者

}

@enduml